<?php

namespace Database\Seeders;

use App\Models\Manufacturer;
use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $manufacturers = [
            ['name' => 'Roche Pharmaceuticals', 'slug' => 'roche-pharmaceuticals', 'country' => 'Switzerland', 'website' => 'https://www.roche.com'],
            ['name' => 'Novartis AG', 'slug' => 'novartis-ag', 'country' => 'Switzerland', 'website' => 'https://www.novartis.com'],
            ['name' => 'Pfizer Inc.', 'slug' => 'pfizer-inc', 'country' => 'United States', 'website' => 'https://www.pfizer.com'],
            ['name' => 'AstraZeneca PLC', 'slug' => 'astrazeneca-plc', 'country' => 'United Kingdom', 'website' => 'https://www.astrazeneca.com'],
            ['name' => 'Bayer AG', 'slug' => 'bayer-ag', 'country' => 'Germany', 'website' => 'https://www.bayer.com'],
        ];

        $ids = [];
        foreach ($manufacturers as $m) {
            $record = Manufacturer::updateOrCreate(['name' => $m['name']], $m);
            $ids[$m['name']] = $record->id;
        }

        $products = [
            [
                'internal_product_id' => 'ONC-001',
                'brand_name' => 'Tecentriq',
                'generic_inn_name' => 'atezolizumab',
                'other_name' => 'RG7446',
                'therapeutic_category' => 'Oncology',
                'subcategory' => 'Lung cancer',
                'dosage_form' => 'Injection',
                'strength' => '840 mg',
                'pack_size_spec' => '1 vial per pack',
                'route_admin' => 'Injection',
                'manufacturer_id' => $ids['Roche Pharmaceuticals'],
                'country_of_origin' => 'Switzerland',
                'legal_status' => 'Prescription only',
                'active_ingredients' => 'atezolizumab 840mg',
                'short_description' => 'Tecentriq is a programmed death-ligand 1 (PD-L1) blocking antibody used to treat several cancers. It helps the immune system detect and attack tumour cells. The product is supplied as a sterile concentrate for intravenous infusion. Healthcare professionals must follow local oncology protocols and monitor patients for immune-mediated adverse reactions during treatment.',
                'full_description' => 'Tecentriq is a fully humanised, engineered monoclonal antibody of immunoglobulin G1 (IgG1) isotype that binds to PD-L1 and inhibits its interaction with PD-1 and B7.1 receptors. This restores anti-tumour T-cell activity. It is approved in combination or as monotherapy for urothelial carcinoma and non-small cell lung cancer.',
                'approved_indication' => 'Urothelial carcinoma and non-small cell lung cancer as monotherapy or in combination with bevacizumab, paclitaxel and carboplatin.',
                'product_images' => ['images/products/tecentriq-840mg.jpg'],
                'image_alt_text' => 'Tecentriq vial and packaging',
                'dosage_admin_text' => '840 mg intravenous infusion over 60 minutes every 2 weeks until disease progression or unacceptable toxicity.',
                'safety_info' => 'Warnings include immune-mediated pneumonitis, hepatitis, colitis, endocrinopathies and infusion-related reactions. Monitor liver and thyroid function.',
                'drug_interactions' => 'No formal drug interaction studies completed; use caution with immunosuppressive agents.',
                'precautions' => 'Use in pregnancy only if benefit outweighs risk; not recommended during breastfeeding.',
                'storage_conditions' => 'Store at 2-8°C, protect from light. Do not freeze.',
                'availability_status' => 'Information available',
                'country_market' => ['Global'],
                'page_language' => 'English',
                'enquiry_contact_link' => '/professional-enquiry',
                'url_slug' => 'tecentriq-840mg',
                'seo_title' => 'Tecentriq 840mg - Roche',
                'meta_description' => 'Tecentriq atezolizumab 840mg injection for oncology treatment.',
                'official_source_url' => 'https://www.roche.com/products',
                'last_verified_date' => '2026-09-01',
                'content_status' => 'Published',
                'reviewer_approver' => 'Admin User',
                'has_known_interactions' => true,
                'has_precautions' => true,
                'information_disclaimer' => 'This product information is provided for educational purposes only and is not a substitute for professional medical advice.',
            ],
            [
                'internal_product_id' => 'HEP-001',
                'brand_name' => 'Baraclude',
                'generic_inn_name' => 'entecavir',
                'other_name' => null,
                'therapeutic_category' => 'Hepatology',
                'subcategory' => 'Hepatitis B',
                'dosage_form' => 'Tablet',
                'strength' => '0.5 mg',
                'pack_size_spec' => '30 tablets per pack',
                'route_admin' => 'Oral',
                'manufacturer_id' => $ids['Bayer AG'],
                'country_of_origin' => 'United States',
                'legal_status' => 'Prescription only',
                'active_ingredients' => 'entecavir 0.5mg',
                'short_description' => 'Baraclude is an antiviral medicine that helps prevent hepatitis B virus from multiplying in the body. It is used for chronic hepatitis B infection in adults with active viral replication. Patients should take it on an empty stomach and continue treatment as directed by their healthcare provider.',
                'full_description' => 'Entecavir is a guanosine nucleoside analogue with potent activity against hepatitis B virus polymerase. It is phosphorylated to the active triphosphate form, which competes with the natural substrate.',
                'approved_indication' => 'Chronic hepatitis B virus infection in adults with evidence of active viral replication.',
                'product_images' => ['images/products/baraclude-0-5mg.jpg'],
                'image_alt_text' => 'Baraclude tablet pack',
                'dosage_admin_text' => '0.5 mg once daily on an empty stomach, at least 2 hours before or after a meal.',
                'safety_info' => 'Severe acute exacerbations of hepatitis may occur upon discontinuation. Lactic acidosis and severe hepatomegaly with steatosis reported.',
                'drug_interactions' => 'No significant drug interactions documented; adjust dose in renal impairment.',
                'precautions' => 'HIV co-infection should be excluded or treated appropriately.',
                'storage_conditions' => 'Store below 30°C in original packaging.',
                'availability_status' => 'Information available',
                'country_market' => ['United States', 'European Union'],
                'page_language' => 'English',
                'enquiry_contact_link' => '/professional-enquiry',
                'url_slug' => 'baraclude-0-5mg',
                'seo_title' => 'Baraclude 0.5mg - Entecavir',
                'meta_description' => 'Baraclude entecavir 0.5mg tablet for chronic hepatitis B.',
                'official_source_url' => null,
                'last_verified_date' => null,
                'content_status' => 'Draft',
                'reviewer_approver' => 'Admin User',
                'has_known_interactions' => true,
                'has_precautions' => true,
                'information_disclaimer' => 'This product information is provided for educational purposes only and is not a substitute for professional medical advice.',
            ],
            [
                'internal_product_id' => 'DIA-001',
                'brand_name' => 'Januvia',
                'generic_inn_name' => 'sitagliptin',
                'other_name' => null,
                'therapeutic_category' => 'Diabetes',
                'subcategory' => 'Type 2 diabetes',
                'dosage_form' => 'Tablet',
                'strength' => '100 mg',
                'pack_size_spec' => '28 tablets per pack',
                'route_admin' => 'Oral',
                'manufacturer_id' => $ids['Pfizer Inc.'],
                'country_of_origin' => 'United States',
                'legal_status' => 'Prescription only',
                'active_ingredients' => 'sitagliptin 100mg',
                'short_description' => 'Januvia is an oral diabetes medicine that helps control blood sugar levels. It is used in adults with type 2 diabetes, often together with diet and exercise. The medication works by increasing incretin levels to stimulate insulin release after meals. Patients must follow the prescribed regimen and monitoring plan.',
                'full_description' => 'Sitagliptin is a dipeptidyl peptidase-4 (DPP-4) inhibitor that increases and prolongs the action of incretin hormones, which stimulate insulin release in response to meals.',
                'approved_indication' => 'Adjunct to diet and exercise to improve glycaemic control in adults with type 2 diabetes.',
                'product_images' => ['images/products/januvia-100mg.jpg'],
                'image_alt_text' => 'Januvia 100mg tablet blister pack',
                'dosage_admin_text' => '100 mg once daily, with or without food. Adjust in renal impairment.',
                'safety_info' => 'Monitor for pancreatitis. Rare cases of severe joint pain and bullous pemphigoid reported.',
                'drug_interactions' => 'No clinically meaningful interactions with metformin or sulfonylureas.',
                'precautions' => 'Renal dosing required for moderate to severe impairment.',
                'storage_conditions' => 'Store at room temperature, 20-25°C.',
                'availability_status' => 'Information available',
                'country_market' => ['Global'],
                'page_language' => 'English',
                'enquiry_contact_link' => '/professional-enquiry',
                'url_slug' => 'januvia-100mg',
                'seo_title' => 'Januvia 100mg - Sitagliptin',
                'meta_description' => 'Januvia sitagliptin 100mg tablet for type 2 diabetes.',
                'official_source_url' => 'https://www.merck.com/',
                'last_verified_date' => '2026-08-15',
                'content_status' => 'Published',
                'reviewer_approver' => 'Admin User',
                'has_known_interactions' => true,
                'has_precautions' => true,
                'information_disclaimer' => 'This product information is provided for educational purposes only and is not a substitute for professional medical advice.',
            ],
            [
                'internal_product_id' => 'CARD-001',
                'brand_name' => 'Lipitor',
                'generic_inn_name' => 'atorvastatin',
                'other_name' => null,
                'therapeutic_category' => 'Cardiovascular',
                'subcategory' => 'Dyslipidaemia',
                'dosage_form' => 'Tablet',
                'strength' => '20 mg',
                'pack_size_spec' => '30 tablets per pack',
                'route_admin' => 'Oral',
                'manufacturer_id' => $ids['Pfizer Inc.'],
                'country_of_origin' => 'United States',
                'legal_status' => 'Prescription only',
                'active_ingredients' => 'atorvastatin 20mg',
                'short_description' => 'Lipitor is a statin used to lower blood cholesterol and reduce cardiovascular risk. It works by inhibiting HMG-CoA reductase, a key enzyme in cholesterol production. The medicine should be combined with a cholesterol-lowering diet and regular monitoring of lipid levels. Dose adjustments are made by the prescriber.',
                'full_description' => 'Atorvastatin is a selective, competitive inhibitor of HMG-CoA reductase. It reduces plasma cholesterol and lipoprotein levels by inhibiting cholesterol synthesis and increasing hepatic LDL receptor activity.',
                'approved_indication' => 'Hyperlipidaemia and prevention of cardiovascular events in patients at risk.',
                'product_images' => ['images/products/lipitor-20mg.jpg'],
                'image_alt_text' => 'Lipitor 20mg tablet bottle',
                'dosage_admin_text' => '10-80 mg once daily. Adjust based on LDL-C goals and tolerability.',
                'safety_info' => 'Muscle pain, weakness and rhabdomyolysis possible. Monitor liver enzymes. Contraindicated in active liver disease.',
                'drug_interactions' => 'Strong CYP3A4 inhibitors such as clarithromycin and itraconazole increase exposure.',
                'precautions' => 'Avoid grapefruit juice. Use effective contraception during treatment.',
                'storage_conditions' => 'Store at room temperature, 20-25°C.',
                'availability_status' => 'Information available',
                'country_market' => ['Global'],
                'page_language' => 'English',
                'enquiry_contact_link' => '/professional-enquiry',
                'url_slug' => 'lipitor-20mg',
                'seo_title' => 'Lipitor 20mg - Atorvastatin',
                'meta_description' => 'Lipitor atorvastatin 20mg tablet for cholesterol management.',
                'official_source_url' => 'https://www.pfizer.com/',
                'last_verified_date' => '2026-08-20',
                'content_status' => 'Approved',
                'reviewer_approver' => 'Admin User',
                'has_known_interactions' => true,
                'has_precautions' => true,
                'information_disclaimer' => 'This product information is provided for educational purposes only and is not a substitute for professional medical advice.',
            ],
            [
                'internal_product_id' => 'RESP-001',
                'brand_name' => 'Symbicort',
                'generic_inn_name' => 'budesonide / formoterol',
                'other_name' => null,
                'therapeutic_category' => 'Respiratory',
                'subcategory' => 'Asthma',
                'dosage_form' => 'Inhalation',
                'strength' => '160/4.5 mcg',
                'pack_size_spec' => '1 inhaler per pack',
                'route_admin' => 'Inhalation',
                'manufacturer_id' => $ids['AstraZeneca PLC'],
                'country_of_origin' => 'United Kingdom',
                'legal_status' => 'Prescription only',
                'active_ingredients' => 'budesonide 160 mcg, formoterol fumarate dihydrate 4.5 mcg',
                'short_description' => 'Symbicort is a combination inhaler containing budesonide and formoterol. It helps prevent and control symptoms of asthma and chronic obstructive pulmonary disease. Patients should rinse the mouth after each use to reduce the risk of oral thrush. The dose must be individualised by the prescribing clinician.',
                'full_description' => 'Budesonide is an inhaled corticosteroid with potent anti-inflammatory activity. Formoterol is a long-acting beta2-agonist that produces bronchodilation. The combination provides both maintenance and reliever therapy.',
                'approved_indication' => 'Asthma and COPD maintenance treatment in adults and adolescents.',
                'product_images' => ['images/products/symbicort-160-4-5mcg.jpg'],
                'image_alt_text' => 'Symbicort inhaler device',
                'dosage_admin_text' => 'Two inhalations twice daily. Additional inhalations may be used for symptom relief.',
                'safety_info' => 'Paradoxical bronchospasm, candida infections and pneumonia in COPD patients possible. Use with caution in severe cardiovascular disorders.',
                'drug_interactions' => 'Beta-blockers may antagonise formoterol; ketoconazole may increase budesonide exposure.',
                'precautions' => 'Rinse mouth after use. Not for acute bronchospasm.',
                'storage_conditions' => 'Store below 30°C with mouthpiece cover on.',
                'availability_status' => 'Information available',
                'country_market' => ['European Union', 'Canada'],
                'page_language' => 'English',
                'enquiry_contact_link' => '/professional-enquiry',
                'url_slug' => 'symbicort-160-4-5mcg',
                'seo_title' => 'Symbicort 160/4.5mcg - AstraZeneca',
                'meta_description' => 'Symbicort budesonide formoterol inhaler for asthma and COPD.',
                'official_source_url' => 'https://www.astrazeneca.com/',
                'last_verified_date' => '2026-09-02',
                'content_status' => 'Published',
                'reviewer_approver' => 'Admin User',
                'has_known_interactions' => true,
                'has_precautions' => true,
                'information_disclaimer' => 'This product information is provided for educational purposes only and is not a substitute for professional medical advice.',
            ],
        ];

        foreach ($products as $data) {
            Product::updateOrCreate(
                ['internal_product_id' => $data['internal_product_id']],
                $data
            );
        }
    }
}
